### ISSUE TITLE
repo out of date?

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [mvturnho/OpenHaspDesigner#3]
Hi,
it seems this repo is not up to date?
because the designer hosted at https://haspdesigner.qrisonline.nl/ has more features (items) than the one available by running this repo.
(also importing page 0 does not work with this repo but does with the online one - and image items break the export with the online one but not with this one)

could you please update this repo to be up to date with your development progress?

cheers!

**Comment by mvturnho** [comment]
Hi Mr. SCHNITZEL,

I updated the repo with my last changes, I hope you join in to fix the issues you pointed out.

greetings.

**Comment by tofuSCHNITZEL** [comment]
Great thanks!
I don't want to make any promises, because I just finished my openhasp project.
