### ISSUE TITLE
Arc type error

### ISSUE THREAD

**Issue by aperfectcypher** [mvturnho/OpenHaspDesigner#4]
When setting an arc object to type "Normal" and then exporting the config, the arc type value is exported as "1" (symmetrical).
It should be "0".

![image](https://github.com/mvturnho/OpenHaspDesigner/assets/53291236/1fd60009-780f-4195-8057-8cea96826ca1)

![image](https://github.com/mvturnho/OpenHaspDesigner/assets/53291236/16e4debd-2584-4e98-ba15-d8d60acfebce)

**Comment by mvturnho** [comment]
I have some major changes coming. The Arc and other widgets had a full redesign. I wil update te online version this week. Also you can then test your design directly on your device with an MQTT jsonl command.

**Comment by aperfectcypher** [comment]
Awesome to hear! Looking forward to testing the new changes.
